import { useState, useCallback } from 'react'
import { createPortal } from 'react-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useDropzone } from 'react-dropzone'
import { FileText, Upload, Trash2, Eye, Download, RefreshCw, Clock, Sparkles, X } from 'lucide-react'
import { DocumentsAPI } from '../utils/api'
import toast from 'react-hot-toast'
import { formatDistanceToNow } from 'date-fns'

function safeTimeAgo(dateStr) {
    try {
        if (!dateStr) return ''
        const d = new Date(dateStr.endsWith('Z') ? dateStr : dateStr + 'Z')
        if (isNaN(d.getTime())) return ''
        return formatDistanceToNow(d, { addSuffix: true })
    } catch { return '' }
}

/* ─── Download AI Summary as .txt ─────────────────── */
function downloadSummary(doc) {
    if (!doc.summary) {
        toast.error('No AI summary available yet')
        return
    }
    const text = `AI Summary — ${doc.original_name}\n${'═'.repeat(50)}\n\n${doc.summary}\n\n---\nGenerated by Knowledge Vault AI`
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${(doc.original_name || 'document').replace(/\.[^.]+$/, '')}_summary.txt`
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
    toast.success('Summary downloaded')
}

/* ─── Upload Zone ─────────────────────────────────── */
function UploadZone({ onUpload, uploading }) {
    const onDrop = useCallback(files => { if (files[0]) onUpload(files[0]) }, [onUpload])
    const { getRootProps, getInputProps, isDragActive } = useDropzone({
        onDrop,
        accept: {
            'application/pdf': ['.pdf'],
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'],
            'text/plain': ['.txt'],
        },
        maxFiles: 1,
        disabled: uploading,
    })

    return (
        <div
            {...getRootProps()}
            style={{
                borderRadius: 16, padding: '32px 24px', textAlign: 'center',
                cursor: uploading ? 'not-allowed' : 'pointer', transition: 'all 0.2s',
                border: `2px dashed ${isDragActive ? 'var(--accent)' : 'var(--border-bright)'}`,
                background: isDragActive ? 'var(--glow)' : 'var(--bg-card)',
            }}
        >
            <input {...getInputProps()} />
            <Upload size={28} style={{ display: 'block', margin: '0 auto 10px', color: isDragActive ? 'var(--accent)' : 'var(--text-dim)' }} />
            <p style={{ fontSize: 14, fontWeight: 600, marginBottom: 4 }}>
                {uploading ? 'Uploading…' : isDragActive ? 'Drop it!' : 'Drop a document here'}
            </p>
            <p style={{ fontSize: 12, color: 'var(--text-dim)' }}>PDF, DOCX, or TXT · AI auto-summarises</p>
            {uploading && <span className="spinner" style={{ display: 'block', margin: '10px auto 0' }} />}
        </div>
    )
}

/* ─── Doc Modal ───────────────────────────────────── */
function DocModal({ doc, onClose }) {
    const [rescanning, setRescanning] = useState(false)
    const qc = useQueryClient()

    const handleRescan = async () => {
        setRescanning(true)
        try {
            await DocumentsAPI.rescan(doc.id)
            toast.success('AI processing started…')
            setTimeout(() => { qc.invalidateQueries(['documents']); setRescanning(false) }, 2000)
        } catch { toast.error('Rescan failed'); setRescanning(false) }
    }

    return createPortal(
        <div className="modal-overlay" onClick={e => e.target === e.currentTarget && onClose()}>
            <div className="modal-content" style={{ maxWidth: 560 }}>
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20, gap: 12 }}>
                    <div style={{ display: 'flex', gap: 14, alignItems: 'center', minWidth: 0, flex: 1 }}>
                        <div style={{
                            width: 40, height: 40, borderRadius: 10, flexShrink: 0,
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            background: 'var(--glow-purple)', border: '1px solid var(--border)',
                        }}>
                            <FileText size={18} color="var(--accent-2)" />
                        </div>
                        <div style={{ minWidth: 0, flex: 1 }}>
                            <h2 style={{
                                fontFamily: 'var(--font-display)', fontSize: 15, fontWeight: 700, marginBottom: 3,
                                overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                            }}>{doc.original_name}</h2>
                            <span style={{ fontSize: 12, color: 'var(--text-dim)' }}>
                                {(doc.file_size / 1024).toFixed(1)} KB
                                {safeTimeAgo(doc.updated_at || doc.created_at) && (
                                    <> · {safeTimeAgo(doc.updated_at || doc.created_at)}</>
                                )}
                            </span>
                        </div>
                    </div>
                    <button className="btn btn-ghost btn-icon" onClick={onClose} style={{ flexShrink: 0 }}>
                        <X size={16} />
                    </button>
                </div>

                {/* Summary */}
                {doc.summary ? (
                    <div style={{
                        borderRadius: 12, padding: 18, marginBottom: 16,
                        background: 'var(--glow)', border: '1px solid var(--border)',
                    }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 10, fontSize: 11, fontWeight: 600, color: 'var(--accent)' }}>
                            <Sparkles size={12} /> AI Summary
                        </div>
                        <p style={{ fontSize: 13, lineHeight: 1.7, color: 'var(--text-secondary)' }}>{doc.summary}</p>
                    </div>
                ) : (
                    <div style={{
                        borderRadius: 12, padding: 18, textAlign: 'center', marginBottom: 16,
                        background: 'var(--bg-card)', border: '1px solid var(--border)',
                    }}>
                        <p style={{ fontSize: 13, marginBottom: 12, color: 'var(--text-dim)' }}>
                            {doc.extracted_text ? 'No summary yet.' : 'Document still processing…'}
                        </p>
                        <button className="btn btn-ghost btn-sm" onClick={handleRescan} disabled={rescanning}>
                            <RefreshCw size={12} /> {rescanning ? 'Processing…' : 'Generate AI Summary'}
                        </button>
                    </div>
                )}

                {/* Download Summary */}
                <button
                    className="btn btn-primary"
                    onClick={() => downloadSummary(doc)}
                    disabled={!doc.summary}
                    style={{ width: '100%', justifyContent: 'center', height: 44 }}
                >
                    <Download size={15} /> Download AI Summary
                </button>
            </div>
        </div>,
        document.body
    )
}

/* ─── Ext colour helper ───────────────────────────── */
const extColor = name => {
    const e = (name || '').split('.').pop().toLowerCase()
    if (e === 'pdf') return '#f87171'
    if (e === 'docx') return '#a78bfa'
    return '#34d399'
}

/* ─── Documents Page ─────────────────────────────── */
export default function DocumentsPage() {
    const [selectedDoc, setSelectedDoc] = useState(null)
    const [uploading, setUploading] = useState(false)
    const qc = useQueryClient()

    const { data: docs = [], isLoading } = useQuery({
        queryKey: ['documents'],
        queryFn: () => DocumentsAPI.getAll().then(r => r.data),
    })

    const deleteMutation = useMutation({
        mutationFn: id => DocumentsAPI.delete(id),
        onSuccess: () => { qc.invalidateQueries(['documents']); qc.invalidateQueries(['dashboard-stats']); toast.success('Deleted') },
    })

    const handleUpload = async (file) => {
        setUploading(true)
        try {
            await DocumentsAPI.upload(file)
            qc.invalidateQueries(['documents'])
            qc.invalidateQueries(['dashboard-stats'])
            toast.success('Uploaded! AI is processing…')
        } catch (err) { toast.error(err.response?.data?.detail || 'Upload failed') }
        finally { setUploading(false) }
    }

    const viewDoc = async (doc) => {
        const { data } = await DocumentsAPI.getById(doc.id)
        setSelectedDoc(data)
    }

    return (
        <div className="animate-in" style={{ maxWidth: '100%', overflow: 'hidden' }}>
            <div className="page-header">
                <h1>Documents</h1>
                <p>Upload and AI-analyse your documents</p>
            </div>

            <div style={{ marginBottom: 24 }}>
                <UploadZone onUpload={handleUpload} uploading={uploading} />
            </div>

            {isLoading ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                    {[...Array(3)].map((_, i) => <div key={i} className="skeleton" style={{ height: 72 }} />)}
                </div>
            ) : docs.length ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10, width: '100%' }}>
                    {docs.map(doc => (
                        <div
                            key={doc.id}
                            className="glass"
                            style={{
                                display: 'flex', alignItems: 'center', gap: 14,
                                padding: '14px 16px', transition: 'transform 0.2s',
                                width: '100%', maxWidth: '100%', overflow: 'hidden',
                            }}
                            onMouseEnter={e => e.currentTarget.style.transform = 'translateX(3px)'}
                            onMouseLeave={e => e.currentTarget.style.transform = 'translateX(0)'}
                        >
                            {/* Ext badge */}
                            <div style={{
                                width: 38, height: 38, borderRadius: 10, flexShrink: 0,
                                display: 'flex', alignItems: 'center', justifyContent: 'center',
                                fontSize: 10, fontFamily: 'var(--font-display)', fontWeight: 700,
                                background: `${extColor(doc.original_name)}18`,
                                border: `1px solid ${extColor(doc.original_name)}28`,
                                color: extColor(doc.original_name),
                            }}>
                                {(doc.original_name || '').split('.').pop().toUpperCase()}
                            </div>

                            {/* Info */}
                            <div style={{ flex: '1 1 0%', minWidth: 0, width: 0 }}>
                                <div style={{
                                    fontSize: 13, fontWeight: 600, marginBottom: 3,
                                    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: '100%',
                                }}>{doc.original_name}</div>
                                <div style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: 12, color: 'var(--text-dim)', flexWrap: 'wrap' }}>
                                    <span>{(doc.file_size / 1024).toFixed(1)} KB</span>
                                    {doc.summary
                                        ? <span style={{ color: 'var(--accent-3)', display: 'flex', alignItems: 'center', gap: 3 }}><Sparkles size={10} /> AI Ready</span>
                                        : <span style={{ color: 'var(--accent-warm)' }}>Processing…</span>}
                                    {safeTimeAgo(doc.created_at) && (
                                        <span style={{ display: 'flex', alignItems: 'center', gap: 3 }}>
                                            <Clock size={10} /> {safeTimeAgo(doc.created_at)}
                                        </span>
                                    )}
                                </div>
                            </div>

                            {/* Actions */}
                            <div style={{ display: 'flex', gap: 6, flexShrink: 0 }}>
                                <button
                                    className="btn btn-ghost btn-sm"
                                    onClick={(e) => { e.stopPropagation(); downloadSummary(doc) }}
                                    title="Download AI Summary"
                                    disabled={!doc.summary}
                                >
                                    <Download size={12} />
                                </button>
                                <button className="btn btn-ghost btn-sm" onClick={() => viewDoc(doc)}>
                                    <Eye size={12} /> View
                                </button>
                                <button className="btn btn-danger btn-sm"
                                    onClick={() => deleteMutation.mutate(doc.id)} disabled={deleteMutation.isPending}>
                                    <Trash2 size={12} />
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            ) : (
                <div className="empty-state">
                    <FileText size={48} />
                    <h3>No documents yet</h3>
                    <p style={{ fontSize: 13 }}>Upload a PDF, DOCX, or TXT and let AI summarise it.</p>
                </div>
            )}

            {selectedDoc && <DocModal doc={selectedDoc} onClose={() => setSelectedDoc(null)} />}
        </div>
    )
}